[tox]
envlist = py{310,311,312,313,314},codechecks

[testenv]
usedevelop = true
deps=
    pytest
    pytest-cov
    coveralls
commands = py.test {posargs: tests/ -v --cov wait_for}

[testenv:codechecks]
skip_install = true
deps = flake8
commands = flake8 {posargs:wait_for tests}

[flake8]
max_line_length = 100
ignore = E128,E811

[travis]
python =
  3.10: py310,codechecks
  3.11: py311,codechecks
  3.12: py312,codechecks
  3.13: py313,codechecks
  3.14: py314,codechecks

